browser=chrome
# change headless to false if you want to see the browser during test execution
# change it to true if you want to run the tests in headless mode for Git Actions, CI/CD pipelines
headless=true