name: Selenium Actions Runner created by omkar on 11 June 2026

on:
  workflow_dispatch:

  schedule:
    - cron: '15 18 * * *' # Runs every day at 18:15 UTC (adjust as needed)   
  

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: temurin

    - name: setup chrome
      uses: browser-actions/setup-chrome@latest


    - name: Build and run tests with Maven
      run: mvn clean test

    - name: email test report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Selenium Test Report
        body: Please find the attached test report.
        to: ompalande123@gmail.com
        from: Github actions automation loader 
